name: 'dbt_object_mgmt'
version: '0.2.5'
config-version: 2

target-path: "target"
macro-paths: ["macros"]
log-path: "logs"
clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt_modules"

vars:
  snowflake_user_file: snowflake/users/users.yml
  snowflake_network_policy_file: snowflake/policy/network_policies.yml
  snowflake_admin: securityadmin
